### ISSUE TITLE
Zone Name Links not Updating on Location Change

### ISSUE THREAD

**Issue by LuxGracetail** [lensvol/fl-oneclick-wiki#16]
On Chrome and Chromium variants (in my case Vivaldi, but generalising - I haven't tested any other browsers) the Location link in the sidebar, i.e. 
>It's [Display Name]!
>Welcome to
>[Area]
>delicious friend!

does not update on moving (this happens whether or not the setting changes as well).

**Comment by LuxGracetail** [comment]
![image](https://user-images.githubusercontent.com/5391063/194734845-b2965d93-4e31-4056-a9a6-7458efb287f1.png)
Example of console logs for movement from Spite to Wolfstack Docks on Chrome.  Interestingly, changing the width of the browser to force Mobile mode and then switching back to full desktop mode causes an update.

**Comment by lensvol** [comment]
Was fixed in 1.8.3.
