### ISSUE TITLE
Feature Request: Extension to Myself & Plans

### ISSUE THREAD

**Issue by Phauks** [lensvol/fl-oneclick-wiki#18]
Could you make it so that qualities on the "Myself" tab, and items and qualities on the "Plans" tabs, open their appropriate places in the Wiki? This would be a similar or identical function to what happens when you click an item quality in the "Story" tab.

**Comment by lensvol** [comment]
I think it can be done, thanks for the idea!

**Comment by lensvol** [comment]
Implemented in version 1.8.4, soon to be distributed through the stores.
