### ISSUE TITLE
Encode titles as URI components

### ISSUE THREAD

**Issue by thorsb** [lensvol/fl-oneclick-wiki#2]
From what i can gather, the extension currently has special handling of ` ` and `'` characters in the titles, but some titles have other special characters. (Example: What will you do with your Hungover Terrier?)
It should be possible to use `encodeURIComponent()`([link](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent)) to encode titles before linking them.
[This](https://github.com/MadeOfMagicAndWires/userscripts/blob/05ac27653e4f6985cd6e2b4015b09fb1baa93ecb/fallen-london-wiki-links/fallen-london-wiki-linking.user.js#L39) userscript does so in the function `encodeLink()` after first replacing the spaces with underscores.

**Comment by lensvol** [comment]
Good catch, thank you! Will release a fix soon.

**Comment by lensvol** [comment]
Fixed in https://github.com/lensvol/fl-oneclick-wiki/commit/2899f414a857dad871d27c6eb22a9cd1086d8dde
