### ISSUE TITLE
[Bug] Colored storylets do not get correctly resolved

### ISSUE THREAD

**Issue by kkotenko** [lensvol/fl-oneclick-wiki#8]
If a storylet has a colored border, the wiki will sort it under e.g. [Category:Gold Storylets](https://fallenlondon.wiki/wiki/Category:Gold_Storylets). 

This extension queries the wiki API for a combination of ID and Category:Storylet, which will return an empty result when the article is in fact in a **sub**category of Category:Storylets - even if the ID is properly stored.

This means that e.g. the storylet "An Exceptional Story: Adornment" gets resolved to [the quality](https://fallenlondon.wiki/wiki/An_Exceptional_Story:_Adornment) of the same name and not the [storylet](https://fallenlondon.wiki/wiki/An_Exceptional_Story:_Adornment_(Storylet)). 

Fortunately, the wiki recently introduced the Semantic Mediawiki property [Has Game Type](https://fallenlondon.wiki/wiki/Property:Has_Game_Type), which can be reliably queried instead, as Template:Action, Template:Card and Template:Storylet set it no matter the color of the option.

Will push a PR in a second.

**Comment by lensvol** [comment]
Wait, but aren't gold frames supposed to be reserved for Fate content only? So what use it will be, given that wiki does not store such content?

I will accept PR nevertheless :)

**Comment by kkotenko** [comment]
Thanks, #9 should work 👍 To clarify: 

1) this affects all cards/storylets with colored border because they are not in Category:Storylets themselves; so this would also affect purple mood cards, silver Ambition storylets, etc.
2) There is a category of gold storylets which is not fate-locked - the introductory storylets for Exceptional stories are freely available. In fact, that was the linked example which prompted my investigation into what's happening :)

Thanks for the extension and a happy New Year to you!

**Comment by lensvol** [comment]
Okay then, I will merge it over the weekend and release a new version :)

Happy New Year to you too! 🎄🎉✨

**Comment by lensvol** [comment]
Looks good, merged it :) Thank you!
